<?php

/**
 * @file
 * Contains restaurant_orders.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function restaurant_orders_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the restaurant_orders module.
    case 'help.page.restaurant_orders':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Restaurant ordering system') . '</p>';
      return $output;

    default:
  }
}
