restaurant_orders.restaurant_tax_type.*:
  type: config_entity
  label: 'Tax type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
