restaurant_orders.restaurant_table.*:
  type: config_entity
  label: 'Table config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    table_zone:
      type: string
      label: 'Table Zone'
    uuid:
      type: string
