restaurant_invoice.payment.*:
  type: config_entity
  label: 'Payment config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    weight:
      type: integer
      label: 'User role weight'
    default_status:
      type: string
      label: 'Default Payment Status'
    uuid:
      type: string
